#!/usr/bin/env python3
"""
run_validation.py — Dynamic Frida validation harness for the 13 selected
PendingIntent candidates. Supports two modes:

  --mode attack (default): Phase A baseline. Installs the real, unmodified
    APK, attaches pendingintent_attack_sim.js, and fires three attacker
    operations (A: fill-in injection, B: privilege-escalation send(),
    C: cancel() hijack) directly against every captured PendingIntent.
    Records whether each executed without a SecurityException.

  --mode defense: reference ownership-gate evaluation. Same three
    operations, same captured PendingIntents, but each is first evaluated
    against a minimal Frida-injected authorisation gate (creator package
    vs. a synthetic non-creator invoker) before being allowed to reach
    the real API. Records BLOCKED_BY_POLICY vs EXECUTED, plus a
    false-positive check confirming the SAME gate still allows the
    creator's own legitimate use. See pendingintent_defense_sim.js for
    the important scope/limitation notes (this runs inside the creator
    app's own process via Frida spawn/hook - it is not a genuine second
    malicious app on a different UID, and is not a bytecode-embedded
    library).

For each selected APK this script:
  1. Installs it on the connected device/emulator via adb.
  2. Launches the app and attaches the selected Frida script, which hooks
     every PendingIntent creation call and evaluates the three operations
     against the captured PendingIntent.
  3. Waits a fixed window (optionally driving the app via BOOT_COMPLETED
     broadcast, widget-update broadcast, JobScheduler force-run, and
     monkey UI events) for the app's normal startup/usage to trigger
     PendingIntent creation (notifications, alarms, widgets, etc.).
  4. Parses the JSON-lines Frida output and records the results.
  5. Writes a consolidated per-app / per-attack results table (CSV + JSON).

IMPORTANT
---------
This harness requires:
  - `adb` on PATH, with exactly one device/emulator connected (or set
    ANDROID_SERIAL / pass --serial).
  - `frida-server` running as root on that device, matching the frida
    client version installed locally (`pip show frida-tools`).
  - The selected_13.csv report already generated by
    analyze_pendingintent_corpus.py.

In --mode attack, this script does NOT install or launch a defensive
framework - it only exercises the baseline (unprotected) exploitation
path; there is nothing to be "blocked". In --mode defense, "blocked"
means the reference gate denied the call before it reached the real
Android API - not that a cross-process/cross-UID Android security
boundary was exercised (Frida attaches within the creator's own process).

Usage
-----
    python run_validation.py                          # attack mode, all 13
    python run_validation.py --mode defense            # defense-gate evaluation, all 13
    python run_validation.py --category v1             # only the v1 group
    python run_validation.py --serial emulator-5554
    python run_validation.py --duration 25              # seconds to observe per app
    python run_validation.py --drive 20                 # seconds of active app-driving
"""

from __future__ import annotations

import argparse
import csv
import json
import subprocess
import sys
import threading
import time
from pathlib import Path
from typing import Any, Dict, List, Optional

BASE_DIR = Path(__file__).resolve().parent.parent
SELECTED_CSV = BASE_DIR / "android_repositories" / "pendingintent_analysis" / "reports" / "selected_13.csv"
SELECTED_ROOT = BASE_DIR / "android_repositories" / "pendingintent_analysis" / "selected_13"
ATTACK_SCRIPT = Path(__file__).resolve().parent / "frida" / "pendingintent_attack_sim.js"
DEFENSE_SCRIPT = Path(__file__).resolve().parent / "frida" / "pendingintent_defense_sim.js"
FORCER_SCRIPT = Path(__file__).resolve().parent / "frida" / "pendingintent_forcer.js"
RESULTS_DIR = Path(__file__).resolve().parent / "results"

DEFAULT_OBSERVE_SECONDS = 20


def run(cmd: List[str], timeout: Optional[int] = None, **kwargs) -> subprocess.CompletedProcess:
    print("  $", " ".join(cmd))
    return subprocess.run(
        cmd, capture_output=True, text=True, timeout=timeout, **kwargs
    )


def check_prereqs(serial: Optional[str]) -> str:
    """Verify adb + a connected device, and the frida CLI. Returns serial."""
    adb_devices = run(["adb", "devices"])
    lines = [l for l in adb_devices.stdout.splitlines()[1:] if l.strip()]
    devices = [l.split()[0] for l in lines if "device" in l]

    if not devices:
        sys.exit(
            "ERROR: no adb device/emulator connected.\n"
            "Start an emulator or connect a rooted device, then run "
            "`adb devices` to confirm it shows up before retrying."
        )

    if serial:
        if serial not in devices:
            sys.exit(f"ERROR: requested serial {serial} not in {devices}")
        return serial

    if len(devices) > 1:
        sys.exit(
            f"ERROR: multiple devices connected ({devices}); "
            "pass --serial to disambiguate."
        )

    return devices[0]


def load_selected(category_filter: Optional[str]) -> List[Dict[str, Any]]:
    if not SELECTED_CSV.exists():
        sys.exit(f"ERROR: {SELECTED_CSV} not found. Run analyze_pendingintent_corpus.py first.")

    with SELECTED_CSV.open(encoding="utf-8") as f:
        rows = list(csv.DictReader(f))

    if category_filter:
        rows = [r for r in rows if r["selected_category"] == category_filter]

    # Resolve to the copied APK path under selected_13/<category>/
    resolved = []
    for r in rows:
        category = r["selected_category"]
        rank = int(r["selected_rank"])
        candidates = sorted((SELECTED_ROOT / category).glob(f"{rank:02d}_*"))
        if not candidates:
            print(f"  WARNING: no copied APK found for {category} rank {rank} ({r['package']})")
            continue
        r["_apk_path"] = candidates[0]
        resolved.append(r)

    return resolved


def install_apk(apk_path: Path, package: str, serial: str) -> bool:
    result = run(["adb", "-s", serial, "install", "-r", "-g", str(apk_path)], timeout=180)
    ok = "Success" in result.stdout
    if not ok:
        print("  INSTALL FAILED:", result.stdout.strip(), result.stderr.strip())
    return ok


def uninstall_apk(package: str, serial: str) -> None:
    run(["adb", "-s", serial, "uninstall", package], timeout=60)


def drive_app(package: str, serial: str, drive_seconds: int) -> None:
    """
    Best-effort trigger layer to coax the target app into actually creating
    a PendingIntent while frida is already attached and observing.

    Many apps only create/schedule a PendingIntent in response to a
    specific event rather than on cold launch:
      - Boot-time alarm scheduling (OnBootCompletedReceiver, WorkManager's
        RescheduleReceiver / SystemAlarmService) - triggered by broadcasting
        ACTION_BOOT_COMPLETED.
      - User-driven scheduling (enabling a setting, subscribing to a feed,
        starting a game session) - approximated generically here with
        `monkey`, which sends pseudo-random touch/key events into the
        app's own process only (-p restricts events to this package), so
        it won't wander into other apps or system UI.

    IMPORTANT: this must run WHILE the frida script from run_frida_attack()
    is already attached and observing, not before it - `frida -f` spawns a
    brand new process, so anything done to the app beforehand is lost when
    frida launches its own fresh instance. Call this from a background
    thread started concurrently with the frida subprocess.

    This is a generic, best-effort driver, not a targeted script per app;
    it increases the chance of observing real PendingIntent creation
    without requiring bespoke UI automation for each of the 13 candidates.
    """
    # 1) Let the app finish laying out its main activity after frida's
    #    spawn+resume.
    time.sleep(2)

    # 2) Broadcast BOOT_COMPLETED - covers apps whose alarms/notifications
    #    are (re)scheduled from a boot receiver or WorkManager's
    #    RescheduleReceiver. Restricted with -p so it only reaches this
    #    package's own registered receivers.
    run([
        "adb", "-s", serial, "shell", "am", "broadcast",
        "-a", "android.intent.action.BOOT_COMPLETED",
        "-p", package,
    ], timeout=15)

    time.sleep(1)

    # 3) Best-effort app-widget update broadcast - covers apps whose
    #    PendingIntents are built inside an AppWidgetProvider.onUpdate()
    #    (e.g. status/toggle widgets). Without a real placed widget this
    #    often no-ops, but it is cheap and harmless to attempt.
    run([
        "adb", "-s", serial, "shell", "am", "broadcast",
        "-a", "android.appwidget.action.APPWIDGET_UPDATE",
        "-p", package,
    ], timeout=15)

    time.sleep(1)

    # 4) Force-run any WorkManager/JobScheduler jobs already registered at
    #    this point (e.g. from BOOT_COMPLETED handling above), before the
    #    UI interaction pass below - some apps schedule their PI-creating
    #    job during Application.onCreate() rather than in response to a
    #    UI action, so this can fire it before we spend the rest of the
    #    budget on monkey.
    force_run_scheduled_jobs(package, serial)

    # 5) Generic UI interaction: pseudo-random touch/key events confined to
    #    this package only, run as ONE continuous pass (not split into
    #    several shorter ones) - some apps only reach their PI-creating
    #    action after navigating several screens deep, which a single
    #    longer run is more likely to reach than multiple short restarts
    #    of monkey's own internal navigation state. Fixed seed keeps this
    #    reproducible run-to-run.
    throttle_ms = 120
    remaining_budget_s = max(4, drive_seconds - 5)
    events = max(15, int((remaining_budget_s * 1000) / throttle_ms))

    run([
        "adb", "-s", serial, "shell", "monkey",
        "-p", package,
        "--pct-touch", "70",
        "--pct-motion", "10",
        "--pct-appswitch", "0",
        "--pct-syskeys", "0",
        "-s", "42",
        "--throttle", str(throttle_ms),
        str(events),
    ], timeout=remaining_budget_s + 15)

    # 6) Force-run jobs again - the UI interaction above may have caused
    #    the app to schedule new work (e.g. tapping "enable" on a feature)
    #    that is now sitting in JobScheduler waiting for its constraints.
    force_run_scheduled_jobs(package, serial)


def force_run_scheduled_jobs(package: str, serial: str) -> None:
    """
    Discover any jobs this package has registered with JobScheduler (this
    is how WorkManager schedules its work under the hood) and force them
    to run immediately, bypassing constraints such as network/battery/idle
    that would otherwise delay them well past the observation window.

    `dumpsys jobscheduler` output contains lines like:
        JOB #10123/42: abc1234 com.example.app/androidx.work...SystemJobService
    where 42 is the job ID needed by `cmd jobscheduler run`.
    """
    result = run(["adb", "-s", serial, "shell", "dumpsys", "jobscheduler"], timeout=15)
    job_ids = set()
    for line in result.stdout.splitlines():
        line = line.strip()
        if not line.startswith("JOB #") or package not in line:
            continue
        # "JOB #10123/42: ..." -> take the part after '/' up to the ':'
        try:
            after_slash = line.split("/", 1)[1]
            job_id = after_slash.split(":", 1)[0].strip()
            if job_id.lstrip("-").isdigit():
                job_ids.add(job_id)
        except (IndexError, ValueError):
            continue

    for job_id in job_ids:
        run([
            "adb", "-s", serial, "shell", "cmd", "jobscheduler",
            "run", "-f", package, job_id,
        ], timeout=15)


def run_frida_attack(package: str, serial: str, duration: int, log_path: Path,
                      drive_seconds: int = 0, script: Path = ATTACK_SCRIPT,
                      force: bool = False) -> str:
    """
    Spawns the app with frida -f <package> -l <script>, lets it run for
    `duration` seconds to trigger PendingIntent creation, then detaches.
    Returns raw combined stdout/stderr text.

    `script` selects which Frida script to load:
      - ATTACK_SCRIPT (default): unprotected baseline, attacks execute
        directly against the real PendingIntent API.
      - DEFENSE_SCRIPT: wraps the same three operations behind a
        reference ownership-authorisation gate (see
        pendingintent_defense_sim.js docstring for scope/limitations).

    `force`, when True, additionally loads pendingintent_forcer.js
    (multiple -l flags are applied by frida-tools in order), which
    directly reflectively invokes the specific app-internal methods
    identified by static analysis as PendingIntent-creating call sites,
    for the subset of candidates where passive/UI-driven observation
    alone did not reach them (see pendingintent_forcer.js docstring).
    """
    cmd = [
        "frida",
        "-D", serial,
        "-f", package,
        "-l", str(script),
    ]
    if force:
        cmd += ["-l", str(FORCER_SCRIPT)]
    cmd += [
        # NOTE: `-f` spawns unpaused by default in this frida-tools version;
        # there is no `--no-pause` flag (only an opt-in `--pause`). Passing
        # a nonexistent flag caused every invocation to fail immediately
        # with "unrecognized arguments" - do not reintroduce it.
        "-q",
        # Quiet mode: run the script then keep the process alive for
        # `-t` seconds instead of dropping into an interactive REPL (which
        # would otherwise block waiting on stdin and never let this
        # harness move on to the next app).
        "-t", str(duration),
    ]

    print("  $", " ".join(cmd), f"  (observing {duration}s"
          + (f", driving for {drive_seconds}s" if drive_seconds else "") + ")")

    try:
        proc = subprocess.Popen(
            cmd,
            stdin=subprocess.PIPE,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
        )
    except FileNotFoundError:
        sys.exit("ERROR: `frida` CLI not found on PATH. Install with `pip install frida-tools`.")

    if drive_seconds > 0:
        # Run the driver concurrently with observation, in a background
        # thread, so it overlaps with frida's attachment window instead of
        # running before or after it.
        driver_thread = threading.Thread(
            target=drive_app, args=(package, serial, drive_seconds), daemon=True
        )
        driver_thread.start()

    output_lines: List[str] = []
    start = time.time()
    try:
        while time.time() - start < duration:
            if proc.poll() is not None:
                break
            line = proc.stdout.readline()
            if line:
                output_lines.append(line)
    finally:
        try:
            proc.terminate()
            proc.wait(timeout=10)
        except Exception:
            proc.kill()

    text = "".join(output_lines)
    log_path.write_text(text, encoding="utf-8")
    return text


def parse_attack_results(raw_output: str) -> List[Dict[str, Any]]:
    events = []
    for line in raw_output.splitlines():
        line = line.strip()
        if not line.startswith("{"):
            continue
        try:
            obj = json.loads(line)
        except json.JSONDecodeError:
            continue
        if obj.get("event") in ("ATTACK_RESULTS", "DEFENSE_RESULTS"):
            events.append(obj)
    return events


def parse_force_events(raw_output: str) -> List[Dict[str, Any]]:
    """Extract FORCE_ATTEMPT/FORCER_INFO/FORCER_ERROR events for diagnostics."""
    events = []
    for line in raw_output.splitlines():
        line = line.strip()
        if not line.startswith("{"):
            continue
        try:
            obj = json.loads(line)
        except json.JSONDecodeError:
            continue
        if obj.get("event") in ("FORCE_ATTEMPT", "FORCER_INFO", "FORCER_ERROR"):
            events.append(obj)
    return events


def summarize(events: List[Dict[str, Any]]) -> Dict[str, str]:
    """
    Collapse all ATTACK_RESULTS/DEFENSE_RESULTS events for one app into a
    single row: per attack (A/B/C):
      - "EXECUTED"         the operation reached the real Android API and
                            completed without exception (attack mode: the
                            attack succeeded; defense mode: the gate
                            allowed it through - should not happen given
                            the synthetic non-creator invoker).
      - "BLOCKED_BY_POLICY" the ownership gate denied the operation before
                            it reached the real API (defense mode only).
      - "NULL_PENDING_INTENT" the factory returned null this capture -
                            nothing to test.
      - "NO_DATA"           no PendingIntent was captured at all in the
                            observation window.
    """
    outcome = {"A": "NO_DATA", "B": "NO_DATA", "C": "NO_DATA", "D": "NO_DATA", "E": "NO_DATA"}
    attack_key_map = {
        "A_fillin_injection": "A",
        "B_privilege_escalation": "B",
        "C_cancel_hijack": "C",
        "D_flood_disruption": "D",
        "E_redirect_probe": "E",
    }

    for ev in events:
        for r in ev.get("data", {}).get("results", []):
            short = attack_key_map.get(r.get("attack"))
            if not short:
                continue
            status = r.get("status")
            if status == "EXECUTED_NO_EXCEPTION":
                outcome[short] = "EXECUTED"
            elif status == "BLOCKED_BY_POLICY" and outcome[short] not in ("EXECUTED",):
                outcome[short] = "BLOCKED_BY_POLICY"
            elif status == "NULL_PENDING_INTENT" and outcome[short] not in ("EXECUTED", "BLOCKED_BY_POLICY"):
                # The factory legitimately returned null this time (e.g.
                # FLAG_NO_CREATE with no existing match) - not an attack
                # failure. Keep looking; a later capture in the same run
                # may still yield a real PendingIntent to attack.
                if outcome[short] == "NO_DATA":
                    outcome[short] = "NULL_PENDING_INTENT"
            elif outcome[short] == "NO_DATA":
                outcome[short] = status or "UNKNOWN"

    return outcome


def check_false_positives(events: List[Dict[str, Any]]) -> Optional[bool]:
    """
    Returns True if every falsePositiveCheck payload observed for this app
    reported allAllowed=True (the ownership gate did not disrupt the
    creator's own legitimate PendingIntent operations), False if any
    check failed, or None if no falsePositiveCheck data was present
    (e.g. running in attack mode, or no PendingIntent was captured).
    """
    seen_any = False
    for ev in events:
        fp = ev.get("data", {}).get("falsePositiveCheck")
        if fp is None:
            continue
        seen_any = True
        if not fp.get("allAllowed", False):
            return False
    return True if seen_any else None


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--category", choices=["v1", "v2", "v3"], default=None,
                         help="Only run this vulnerability category (default: all 13)")
    parser.add_argument("--serial", default=None, help="adb device serial (auto-detected if omitted)")
    parser.add_argument("--duration", type=int, default=DEFAULT_OBSERVE_SECONDS,
                         help="Seconds to observe each app for PendingIntent creation")
    parser.add_argument("--drive", type=int, default=0,
                         help="Seconds to actively drive the app (BOOT_COMPLETED broadcast + "
                              "monkey UI events restricted to this package) before attaching "
                              "the attack script. 0 disables driving (pure passive observation, "
                              "matching the original harness behaviour).")
    parser.add_argument("--keep-installed", action="store_true",
                         help="Do not uninstall the APK after testing")
    parser.add_argument("--force", action="store_true",
                         help="Additionally load pendingintent_forcer.js, which "
                              "reflectively invokes the specific app-internal call "
                              "sites identified by static analysis for candidates "
                              "where passive/UI-driven observation alone does not "
                              "reach PendingIntent creation (NO_DATA/NULL_PENDING_INTENT "
                              "cases). See pendingintent_forcer.js docstring for scope.")
    parser.add_argument("--mode", choices=["attack", "defense"], default="attack",
                         help="'attack': unprotected baseline (pendingintent_attack_sim.js). "
                              "'defense': reference ownership-authorisation gate "
                              "(pendingintent_defense_sim.js) - see that script's docstring "
                              "for what this does and does not prove.")
    args = parser.parse_args()

    RESULTS_DIR.mkdir(parents=True, exist_ok=True)

    serial = check_prereqs(args.serial)
    print(f"Using device: {serial}\n")

    targets = load_selected(args.category)
    if not targets:
        sys.exit("No targets resolved - check selected_13.csv and selected_13/ directory.")

    all_rows = []

    for i, target in enumerate(targets, start=1):
        package = target["package"]
        category = target["selected_category"]
        rank = target["selected_rank"]
        apk_path = target["_apk_path"]

        print(f"\n[{i}/{len(targets)}] {category}-{rank}  {package}  ({apk_path.name})")

        if not install_apk(apk_path, package, serial):
            all_rows.append({
                "category": category, "rank": rank, "package": package,
                "A": "INSTALL_FAILED", "B": "INSTALL_FAILED", "C": "INSTALL_FAILED",
            })
            continue

        script = DEFENSE_SCRIPT if args.mode == "defense" else ATTACK_SCRIPT
        suffix = "_forced" if args.force else ""
        log_path = RESULTS_DIR / f"{args.mode}{suffix}_{category}_{rank}_{package}.log"
        raw = run_frida_attack(package, serial, args.duration, log_path,
                                drive_seconds=args.drive, script=script, force=args.force)
        events = parse_attack_results(raw)
        outcome = summarize(events)
        fp_ok = check_false_positives(events) if args.mode == "defense" else None

        print(f"  PendingIntents captured: {len(events)}")
        print(f"  Attack A (fill-in injection):     {outcome['A']}")
        print(f"  Attack B (privilege escalation):  {outcome['B']}")
        print(f"  Attack C (cancel hijack):         [omitted from this combined run - see note in pendingintent_attack_sim.js]")
        print(f"  Attack D (flood disruption):      {outcome['D']}")
        print(f"  Attack E (redirect probe):        {outcome['E']}")
        if args.mode == "defense":
            print(f"  False-positive check (legit creator-invoked ops still allowed): {fp_ok}")
        if args.force:
            force_events = parse_force_events(raw)
            for fe in force_events:
                d = fe.get("data", {})
                if fe.get("event") == "FORCE_ATTEMPT":
                    print(f"  [force] {d.get('className')}.{d.get('methodName')} -> {d.get('status')}")
                else:
                    print(f"  [force] {fe.get('event')}: {d.get('detail')}")

        row = {
            "category": category, "rank": rank, "package": package,
            "pi_captured": len(events), **outcome,
        }
        if args.mode == "defense":
            row["false_positive_ok"] = fp_ok
        all_rows.append(row)

        if not args.keep_installed:
            uninstall_apk(package, serial)

    # ---- Write consolidated results table ----
    result_suffix = "_forced" if args.force else ""
    out_csv = RESULTS_DIR / f"{args.mode}{result_suffix}_results.csv"
    fieldnames = ["category", "rank", "package", "pi_captured", "A", "B", "C", "D", "E"]
    if args.mode == "defense":
        fieldnames.append("false_positive_ok")
    with out_csv.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames, extrasaction="ignore")
        writer.writeheader()
        writer.writerows(all_rows)

    out_json = RESULTS_DIR / f"{args.mode}{result_suffix}_results.json"
    out_json.write_text(json.dumps(all_rows, indent=2), encoding="utf-8")

    print("\n" + "=" * 70)
    print("VALIDATION COMPLETE" if args.mode == "attack" else "DEFENSE EVALUATION COMPLETE")
    print("=" * 70)
    total = len(all_rows)

    if args.mode == "attack":
        executed_counts = {"A": 0, "B": 0, "C": 0, "D": 0, "E": 0}
        for row in all_rows:
            for k in ("A", "B", "C", "D", "E"):
                if row.get(k) in ("EXECUTED", "COMPLETED"):
                    executed_counts[k] += 1
        print(f"Apps tested: {total}")
        print(f"Attack A (fill-in injection) executed without exception:    {executed_counts['A']}/{total}")
        print(f"Attack B (privilege escalation) executed without exception: {executed_counts['B']}/{total}")
        print(f"Attack C (cancel hijack): omitted from this run - tested separately, see attack_results.csv from the dedicated C-only cross-app run")
        print(f"Attack D (flood disruption) completed:                     {executed_counts['D']}/{total}")
        print(f"Attack E (redirect probe, EXECUTED_NO_EXCEPTION=NOT effective): {executed_counts['E']}/{total}")
    else:
        blocked_counts = {"A": 0, "B": 0, "C": 0}
        had_pi = 0
        fp_pass = 0
        fp_evaluated = 0
        for row in all_rows:
            if row.get("pi_captured", 0) > 0:
                had_pi += 1
            for k in ("A", "B", "C"):
                if row.get(k) == "BLOCKED_BY_POLICY":
                    blocked_counts[k] += 1
            if row.get("false_positive_ok") is not None:
                fp_evaluated += 1
                if row.get("false_positive_ok"):
                    fp_pass += 1
        print(f"Apps tested: {total} (PendingIntent captured in {had_pi})")
        print(f"Attack A (fill-in injection) blocked by policy:    {blocked_counts['A']}/{had_pi if had_pi else total}")
        print(f"Attack B (privilege escalation) blocked by policy: {blocked_counts['B']}/{had_pi if had_pi else total}")
        print(f"Attack C (cancel hijack) blocked by policy:        {blocked_counts['C']}/{had_pi if had_pi else total}")
        print(f"False-positive check passed (legit ops still allowed): {fp_pass}/{fp_evaluated}")
        print(
            "\nNOTE: 'blocked' here means the reference ownership gate denied the\n"
            "operation before it reached the real Android PendingIntent API. This\n"
            "runs inside the creator app's own process (Frida spawn/hook), not a\n"
            "genuine second malicious app/UID - see pendingintent_defense_sim.js\n"
            "docstring for full scope and limitations."
        )
    print(f"\nResults written to: {out_csv}")
    print(f"Raw per-app logs in: {RESULTS_DIR}")


if __name__ == "__main__":
    main()
